module.exports = {
  preset: 'jest-expo',
  setupFiles: ['./jest.setup.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    'src/context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    '../../src/context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    '../src/context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    '../../../src/context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    '../../context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    '../context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    '../../../context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    '../../src/context/ThemeContext': '<rootDir>/__mocks__/ThemeContext.tsx',
    'expo-font': '<rootDir>/__mocks__/expo-font.ts',
    'expo-router': '<rootDir>/__mocks__/expo-router.ts',
    'expo-local-authentication': '<rootDir>/__mocks__/expo-local-authentication.ts',
    'expo-notifications': '<rootDir>/__mocks__/expo-notifications.ts',
    'expo-sharing': '<rootDir>/__mocks__/expo-sharing.ts',
    'expo-file-system': '<rootDir>/__mocks__/expo-file-system.ts',
    'expo-clipboard': '<rootDir>/__mocks__/expo-clipboard.ts',
    'expo-keep-awake': '<rootDir>/__mocks__/expo-keep-awake.ts',
    'expo-localization': '<rootDir>/__mocks__/expo-localization.ts',
    'expo-device': '<rootDir>/__mocks__/expo-device.ts',
    'expo-av': '<rootDir>/__mocks__/expo-av.ts',
    'expo-audio': '<rootDir>/__mocks__/expo-audio.ts',
    'expo-video': '<rootDir>/__mocks__/expo-video.ts',
    'expo-crypto': '<rootDir>/__mocks__/expo-crypto.ts',
    'expo-image': '<rootDir>/__mocks__/expo-image.js',
    'expo-haptics': '<rootDir>/__mocks__/expo-haptics.ts',
    'react-native-svg': '<rootDir>/__mocks__/react-native-svg.ts',
    'react-native-view-shot': '<rootDir>/__mocks__/react-native-view-shot.ts',
    'react-native-webview': '<rootDir>/__mocks__/react-native-webview.ts',
    'i18n': '<rootDir>/__mocks__/i18n.ts',
    '../i18n': '<rootDir>/__mocks__/i18n.ts',
    '../../i18n': '<rootDir>/__mocks__/i18n.ts',
    '../../../i18n': '<rootDir>/__mocks__/i18n.ts',
    '../../../../i18n': '<rootDir>/__mocks__/i18n.ts',
    'src/i18n': '<rootDir>/__mocks__/i18n.ts',
    '../src/i18n': '<rootDir>/__mocks__/i18n.ts',
    '../../src/i18n': '<rootDir>/__mocks__/i18n.ts',
    '../../../src/i18n': '<rootDir>/__mocks__/i18n.ts',
    '../../../../src/i18n': '<rootDir>/__mocks__/i18n.ts',
    'react-native-youtube-iframe': '<rootDir>/__mocks__/react-native-youtube-iframe.ts',
    'react-native-chart-kit': '<rootDir>/__mocks__/react-native-chart-kit.ts',
    '@react-native-async-storage/async-storage': '<rootDir>/__mocks__/async-storage.ts',
    'config/supabase': '<rootDir>/__mocks__/supabase.ts',
    '^test-renderer$': 'react-test-renderer',
    '../../__mocks__/render-hook': '<rootDir>/__mocks__/render-hook.ts',
    '@expo/vector-icons': '<rootDir>/__mocks__/@expo/vector-icons.ts',
    'lucide-react-native': '<rootDir>/__mocks__/lucide-react-native.ts',
  },
  testPathIgnorePatterns: ['/node_modules/', '/android/', '/ios/', '/.expo/', '/e2e/'],
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg|react-native-reanimated|react-native-gesture-handler|react-native-youtube-iframe|react-native-chart-kit|react-native-webview|lucide-react-native|otpauth)',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    'app/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.test.{js,jsx,ts,tsx}',
    '!app/**/*.test.{js,jsx,ts,tsx}',
    '!src/**/index.{js,ts}',
  ],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
};
