module.exports = {
  preset: 'jest-expo',
  setupFiles: ['./jest.setup.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    'expo-font': '<rootDir>/__mocks__/expo-font.js',
    'expo-router': '<rootDir>/__mocks__/expo-router.js',
    'expo-local-authentication': '<rootDir>/__mocks__/expo-local-authentication.js',
    'expo-notifications': '<rootDir>/__mocks__/expo-notifications.js',
    'expo-sharing': '<rootDir>/__mocks__/expo-sharing.js',
    'expo-file-system': '<rootDir>/__mocks__/expo-file-system.js',
    'expo-clipboard': '<rootDir>/__mocks__/expo-clipboard.js',
    'expo-keep-awake': '<rootDir>/__mocks__/expo-keep-awake.js',
    'expo-localization': '<rootDir>/__mocks__/expo-localization.js',
    'expo-device': '<rootDir>/__mocks__/expo-device.js',
    'expo-av': '<rootDir>/__mocks__/expo-av.js',
    'expo-image': '<rootDir>/__mocks__/expo-image.js',
    'expo-location': '<rootDir>/__mocks__/expo-location.js',
    'expo-haptics': '<rootDir>/__mocks__/expo-haptics.js',
    'i18n': '<rootDir>/__mocks__/i18n.js',
    '../i18n': '<rootDir>/__mocks__/i18n.js',
    '../../i18n': '<rootDir>/__mocks__/i18n.js',
    '../../../i18n': '<rootDir>/__mocks__/i18n.js',
    '../../../../i18n': '<rootDir>/__mocks__/i18n.js',
    'src/i18n': '<rootDir>/__mocks__/i18n.js',
    '../src/i18n': '<rootDir>/__mocks__/i18n.js',
    '../../src/i18n': '<rootDir>/__mocks__/i18n.js',
    '../../../src/i18n': '<rootDir>/__mocks__/i18n.js',
    '../../../../src/i18n': '<rootDir>/__mocks__/i18n.js',
    'react-native-youtube-iframe': '<rootDir>/__mocks__/react-native-youtube-iframe.js',
    'react-native-chart-kit': '<rootDir>/__mocks__/react-native-chart-kit.js',
    '@react-native-async-storage/async-storage': '<rootDir>/__mocks__/async-storage.js',
    'config/supabase': '<rootDir>/__mocks__/supabase.js',
    '^test-renderer$': 'react-test-renderer',
    '../../__mocks__/render-hook': '<rootDir>/__mocks__/render-hook.js',
  },
  testPathIgnorePatterns: ['/node_modules/', '/android/', '/ios/', '/.expo/', '/e2e/'],
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg|react-native-reanimated|react-native-gesture-handler|react-native-youtube-iframe|react-native-chart-kit|react-native-webview|lucide-react-native|otpauth)',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    'app/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.test.{js,jsx,ts,tsx}',
    '!app/**/*.test.{js,jsx,ts,tsx}',
    '!src/**/index.{js,ts}',
  ],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
};
