import { StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';
import { SPACING, BORDER_RADIUS } from '../constants/spacing';

export const styles = StyleSheet.create({
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: SPACING.xl, paddingBottom: SPACING.md },
  counter: { fontFamily: 'Montserrat_700Bold', fontSize: 14, color: COLORS.primary },
  progressTrack: { height: 4, backgroundColor: COLORS.surface, marginHorizontal: SPACING.xl, borderRadius: 2, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: COLORS.primary, borderRadius: 2 },
  content: { padding: SPACING.xl },
  exerciseCard: { backgroundColor: COLORS.surface, borderRadius: BORDER_RADIUS.lg, padding: SPACING.xl, alignItems: 'center', borderWidth: 1, borderColor: COLORS.border, marginBottom: SPACING.xl },
  exerciseIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: COLORS.primary + '15', justifyContent: 'center', alignItems: 'center', marginBottom: SPACING.md },
  exerciseName: { fontFamily: 'Montserrat_700Bold', fontSize: 18, color: COLORS.textTitle, marginBottom: 4, textAlign: 'center' },
  exerciseDesc: { fontFamily: 'Inter_400Regular', fontSize: 13, color: COLORS.textMuted, textAlign: 'center', marginBottom: SPACING.lg },
  timerSection: { alignItems: 'center', marginBottom: SPACING.lg, width: '100%' },
  timerValue: { fontFamily: 'Montserrat_800ExtraBold', fontSize: 48, color: COLORS.primary, marginBottom: SPACING.sm },
  timerBar: { height: 6, backgroundColor: COLORS.background, borderRadius: 3, width: '100%', overflow: 'hidden' },
  timerFill: { height: '100%', backgroundColor: COLORS.primary, borderRadius: 3 },
  actions: { width: '100%' },
  startBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: COLORS.primary, borderRadius: BORDER_RADIUS.md, padding: SPACING.md },
  startBtnText: { fontFamily: 'Montserrat_700Bold', fontSize: 14, color: COLORS.background, letterSpacing: 1 },
  skipBtn: { alignItems: 'center', padding: SPACING.md },
  skipBtnText: { fontFamily: 'Montserrat_600SemiBold', fontSize: 13, color: COLORS.textMuted },
  exerciseList: { gap: SPACING.xs },
  exerciseRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: BORDER_RADIUS.md, padding: SPACING.md, borderWidth: 1, borderColor: COLORS.border },
  exerciseRowActive: { borderColor: COLORS.primary, backgroundColor: COLORS.primary + '08' },
  exerciseRowDone: { opacity: 0.5 },
  rowDot: { width: 24, height: 24, borderRadius: 12, backgroundColor: COLORS.background, justifyContent: 'center', alignItems: 'center', marginRight: SPACING.md },
  rowDotDone: { backgroundColor: COLORS.success },
  rowNum: { fontFamily: 'Montserrat_700Bold', fontSize: 11, color: COLORS.textMuted },
  rowText: { flex: 1, fontFamily: 'Inter_600SemiBold', fontSize: 13, color: COLORS.textTitle },
  rowTextDone: { textDecorationLine: 'line-through', color: COLORS.textMuted },
  rowDuration: { fontFamily: 'Montserrat_600SemiBold', fontSize: 12, color: COLORS.textMuted },
  doneBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: COLORS.success, borderRadius: BORDER_RADIUS.md, padding: SPACING.md, marginTop: SPACING.xl },
  doneBtnText: { fontFamily: 'Montserrat_700Bold', fontSize: 14, color: '#fff', letterSpacing: 1 },
});
